AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: nodejs10.x
      CodeUri: ./hello-world
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::407698350389:role/LambdaRole"
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
